# Generated by Django 4.2.16 on 2026-03-12 17:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('product_type', models.CharField(max_length=200)),
                ('unit_type', models.CharField(choices=[('piece', 'Per Piece'), ('kg', 'Per KG'), ('ton', 'Per Ton'), ('bag', 'Per Bag'), ('liter', 'Per Liter'), ('meter', 'Per Meter'), ('feet', 'Per Feet'), ('bundle', 'Per Bundle'), ('other', 'Other')], default='kg', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Price per piece/kg/unit', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('material_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Auto-calculated: unit_price × quantity', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('transport_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='material_cost + labor_cost + transport_cost', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_paid', models.BooleanField(default=False, help_text='Was this paid instantly?')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(blank=True, help_text='e.g. Cash, Bank Transfer, bKash', max_length=50)),
                ('reference', models.CharField(blank=True, help_text='Transaction ID or cheque number', max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
