# Generated by Django 4.2.16 on 2026-03-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factorysalary',
            old_name='bonus_1',
            new_name='bonus',
        ),
        migrations.RemoveField(
            model_name='factorysalary',
            name='bonus_2',
        ),
    ]
