# Generated by Django 4.2.16 on 2026-03-05 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_remove_factorysalary_bonus_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factorysalary',
            name='deductions',
        ),
    ]
