# Generated by Django 4.2.28 on 2026-03-01 16:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('factory', 'Factory'), ('depot', 'Depot')], max_length=10)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('raw_materials', 'Raw Materials'), ('utilities', 'Utilities (Electric/Water/Gas)'), ('transport', 'Transport'), ('maintenance', 'Maintenance & Repairs'), ('fuel', 'Fuel'), ('food', 'Food & Refreshments'), ('office', 'Office Supplies'), ('salary_advance', 'Salary Advance'), ('loading', 'Loading/Unloading'), ('rent', 'Rent'), ('miscellaneous', 'Miscellaneous'), ('other', 'Other')], default='miscellaneous', max_length=20)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depot', models.ForeignKey(blank=True, help_text='Select depot if expense type is Depot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='depot.depot')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
