# Generated by Django 4.2.16 on 2026-03-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depotsalary',
            old_name='bonus_1',
            new_name='bonus',
        ),
        migrations.RemoveField(
            model_name='depotsalary',
            name='bonus_2',
        ),
        migrations.RemoveField(
            model_name='depotsalary',
            name='deductions',
        ),
    ]
